server:
  port: 8082
spring:
  application:
    name: game-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${auth-service.host}/.well-known/jwks.json
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
  flyway:
    enabled: false

